# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'
pod 'Firebase/Analytics'

target 'sportpop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sportpop

  target 'sportpopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sportpopUITests' do
    # Pods for testing
  end

end
